name: CI

on:
  push:
    branches-ignore:
      - 'generated'
      - 'codegen/**'
      - 'integrated/**' 

jobs:
  lint:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    if: github.repository == 'Santhoshreddyva/sambanova-sdk'
    steps:
      - uses: actions/checkout@v4

      - name: Install Rye
        run: |
          curl -sSf https://rye.astral.sh/get | bash
          echo "$HOME/.rye/shims" >> $GITHUB_PATH

      - name: Install dependencies
        run: rye sync --all-features

      - name: Run lints
        run: ./scripts/lint

  upload:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    if: github.repository == 'Santhoshreddyva/sambanova-sdk'
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Twine & Build Tools
        run: |
          pip install --upgrade build twine

      - name: Build SDK
        run: python -m build

      - name: Upload to PyPI
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN }}
        run: twine upload dist/*

  test:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    if: github.repository == 'Santhoshreddyva/sambanova-sdk'
    steps:
      - uses: actions/checkout@v4

      - name: Install Rye
        run: |
          curl -sSf https://rye.astral.sh/get | bash
          echo "$HOME/.rye/shims" >> $GITHUB_PATH

      - name: Bootstrap
        run: ./scripts/bootstrap

  examples:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    if: github.repository == 'Santhoshreddyva/sambanova-sdk'
    steps:
      - uses: actions/checkout@v4

      - name: Install Rye
        run: |
          curl -sSf https://rye.astral.sh/get | bash
          echo "$HOME/.rye/shims" >> $GITHUB_PATH

      - name: Install dependencies
        run: rye sync --all-features

      - name: Run examples
        env: 
          SN_API_KEY: ${{ secrets.SN_API_KEY }}
        run: |
          rye run python examples/chat.py
          rye run python examples/audio.py
